# GitHub Actions 配置文件
# 定义通用的环境变量、工具版本和配置选项

# 工具版本配置
tool_versions:
  bazel: "8.4.0"
  gcc: "latest"
  clang: "18"
  msvc: "latest"
  cmake: "3.28"
  python: "3.12"

# 构建配置
build_config:
  cache_enabled: true
  parallel_jobs: 4
  timeout_minutes: 30
  memory_limit: "4GB"

# 测试配置
test_config:
  unit_tests: true
  integration_tests: true
  performance_tests: true
  coverage_enabled: true
  timeout_minutes: 15

# 代码质量配置
code_quality:
  cppcheck_enabled: true
  clang_tidy_enabled: true
  clang_format_enabled: true
  cpplint_enabled: true
  valgrind_enabled: true

# 安全扫描配置
security:
  bandit_enabled: true
  safety_enabled: true
  dependency_check_enabled: true
  memory_leak_check: true
  buffer_overflow_check: true

# 通知配置
notifications:
  slack_enabled: true
  teams_enabled: true
  email_enabled: true
  webhook_enabled: true
  failure_alerts: true
  success_notifications: false

# 文档配置
documentation:
  doxygen_enabled: true
  sphinx_enabled: true
  github_pages_enabled: true
  auto_deploy: true

# 缓存配置
cache:
  bazel_cache: true
  dependency_cache: true
  build_cache: true
  test_cache: true

# 环境配置
environments:
  development:
    branches: ["develop", "feature/*"]
    auto_approve: false
    required_checks: ["quick-build", "code-quality"]
  
  staging:
    branches: ["main"]
    auto_approve: false
    required_checks: ["ci", "security-scan", "performance"]
  
  production:
    branches: ["main"]
    auto_approve: false
    required_checks: ["ci", "security-scan", "performance", "dependency-scan"]

# 平台支持配置
platforms:
  linux:
    - ubuntu-latest
    - ubuntu-22.04
    - ubuntu-24.04
  windows:
    - windows-latest
  macos:
    - macos-latest  # 可选添加

# 分支保护规则
branch_protection:
  main:
    required_status_checks:
      - ci
      - security-scan
      - code-quality
      - performance
    require_pull_request_reviews: true
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  
  develop:
    required_status_checks:
      - quick-build
      - code-quality
    require_pull_request_reviews: true
    required_approving_review_count: 1
    dismiss_stale_reviews: true

# 定时任务配置
schedules:
  code_quality: "0 2 * * 1"      # 每周一凌晨2点
  security_scan: "0 4 * * 0"     # 每周日凌晨4点
  dependency_scan: "0 5 * * 0"   # 每周日凌晨5点
  performance_test: "0 3 * * 0"  # 每周日凌晨3点

# 资源限制
resource_limits:
  ubuntu_latest:
    cpu: "4"
    memory: "8GB"
    disk: "20GB"
  
  ubuntu_22_04:
    cpu: "4"
    memory: "8GB"
    disk: "20GB"
  
  ubuntu_24_04:
    cpu: "4"
    memory: "8GB"
    disk: "20GB"
  
  windows_latest:
    cpu: "4"
    memory: "8GB"
    disk: "20GB"

# 错误处理配置
error_handling:
  retry_on_failure: true
  max_retries: 3
  retry_delay_minutes: 5
  notify_on_retry: true
  fail_fast: false

# 监控和报告
monitoring:
  performance_metrics: true
  build_time_tracking: true
  resource_usage_monitoring: true
  failure_rate_tracking: true
  weekly_reports: true
